name: Rails
on: push

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: mission_system_5xruby_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby 2.7.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.0

      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get -yqq install libpq-dev build-essential libcurl4-openssl-dev
          wget -c https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          chrome_options = Options()
          chrome_options.add_argument('--no-sandbox')
          chrome_options.add_argument('--headless')
          chrome_options.add_argument('--disable-dev-shm-usage')
          d = webdriver.Chrome('/home/PycharmProjects/chromedriver',chrome_options=chrome_options)
          d.get('https://www.google.nl/')
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
        run: |
          cp config/database.ci.yml config/database.yml
          rake db:create db:migrate

      - name: Run tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          RAILS_ENV: test
        run: rspec
